"""init

Revision ID: 704426a55150
Revises: 
Create Date: 2025-10-30 00:52:11.226582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '704426a55150'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('parent_id IS NULL OR parent_id != id', name='ck_occupations_no_self_parent'),
    sa.ForeignKeyConstraint(['parent_id'], ['occupations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name', name='uq_occupations_parent_name')
    )
    op.create_index(op.f('ix_occupations_parent_id'), 'occupations', ['parent_id'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude  >= -90  AND latitude  <= 90', name='ck_lat_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_lon_range'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_organization_id'), 'buildings', ['organization_id'], unique=True)
    op.create_table('organization_occupations',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('occupation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id', 'occupation_id'),
    sa.UniqueConstraint('org_id', 'occupation_id', name='uq_org_occ')
    )
    op.create_table('phone_numbers',
    sa.Column('value', sa.String(length=16), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('type', sa.Enum('WORK', 'MOBILE', 'FAX', name='phonenumbertype'), server_default='WORK', nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("value ~ '^\\+[0-9]{1,15}$'", name='ck_phone_e164_format'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'value', name='uq_org_phone')
    )
    op.create_index(op.f('ix_phone_numbers_organization_id'), 'phone_numbers', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_numbers_organization_id'), table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_table('organization_occupations')
    op.drop_index(op.f('ix_buildings_organization_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_occupations_parent_id'), table_name='occupations')
    op.drop_table('occupations')
    # ### end Alembic commands ###
